version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: simpledbmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  web:
    build: .
    command: python library/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: web:app
    container_name: django_container
    depends_on:
      - db